name: interpreter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.9.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  file_picker: ^10.3.2
  get: ^4.7.3
  google_fonts: ^8.0.2
  pinput: ^5.0.1
  rename: ^3.1.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.jpeg"
  min_sdk_android: 21 
flutter:
  uses-material-design: true

  assets:
    - assets/logo.jpeg
